### ISSUE TITLE
What's updated in v1.12.3

### ISSUE THREAD

**Issue by vae520283995** [etclabscore/multi-geth#434]
@ziogaschr Hi, There is no description on the release page, I am not sure if I can upgrade from v1.12.2 to v1.12.3

**Comment by ziogaschr** [comment]
Sorry for publishing without the release notes, it has been published by my mistake before I fill the notes and we decided to keep it published until I feel up the details the next day. 
My apologies :)

Check the release notes [here](https://github.com/etclabscore/core-geth/releases/tag/v1.12.3)
