### ISSUE TITLE
 Served admin_peers

### ISSUE THREAD

**Issue by yarema09** [etclabscore/multi-geth#436]
Аfter complete synchronization of the node, the inscription appears
 Served admin_peers conn = 217.12.203.122: 47724 reqid = 1 t = 0s err = "the admin_peers method does not exist / is not available"
 Served parity_netPeers                   conn=217.12.203.122:47724 reqid=1 t=0s        err="the method parity_netPeers does not exist/is not available"

how to fix it and is it important error?

**Comment by 3cl1ps** [comment]
edited, saw this error on my geth logs (last version).
now they seem to have disappear.

but this is the way to trigger it again :
curl --data '{"method":"parity_netPeers","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:1234
{"jsonrpc":"2.0","id":1,"error":{"code":-32601,"message":"the method parity_netPeers does not exist/is not available"}}

**Comment by meowsbits** [comment]
It is possible that someone (someone's robot, more likely) is making that request to your client automatically. You may also see `miner_start`, `miner_setEtherbase`, etc. 
The `admin_` RPC module is _not_ public by default (nor is `miner_`), and `parity_netPeers` method doesn't exist for core-geth.
