### ISSUE TITLE
Breaking change: Unable to run 1.12.3 on Amazon Linux 2

### ISSUE THREAD

**Issue by lukaszsamson** [etclabscore/multi-geth#438]
#### System information

Geth version: `1.12.3`
OS & Version: Amazon linux 2

#### Expected behaviour

Version 1.12.3 works as 1.12.2 did.

#### Actual behaviour
It seems taht minimum required GLIBC was bumped to 2.29
```
/opt/geth-classic-testnet/geth: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /opt/geth-classic-testnet/geth)
```
but on amazon linux 2 only 2.26 is available
```
yum list glibc
Installed Packages
glibc.x86_64                                                                                                  2.26-56.amzn2                                                                                                  @amzn2-core
Available Packages
glibc.i686                                                                                                    2.26-56.amzn2                                                                                                  amzn2-core 
```
Amazon linux 2 is going to be supported until June 30, 2023 (https://aws.amazon.com/amazon-linux-2/faqs/)

**Comment by meowsbits** [comment]
Thanks for this report. Seems indeed like a thing it should do and doesn't. I'll take a look at it. 
In the meantime, a `yum update` (that's pseudo-code, not familiar with yum) doesn't fix it, does it?

**Comment by lukaszsamson** [comment]
> In the meantime, a `yum update` (that's pseudo-code, not familiar with yum) doesn't fix it, does it?

No, Amazon linux 2 is based on Centos 7 and locked to Glibc 2.26
> A set of core packages including systemd, GCC 7.3, Glibc 2.26, Binutils 2.29.1 that receive Long Term Support (LTS) from AWS

BTW this problem does not exist on original geth

**Comment by meowsbits** [comment]
Are you building from source or using a pre-built binary?

**Comment by lukaszsamson** [comment]
pre-built

**Comment by meowsbits** [comment]
Its looking improbable for guaranteed support for CentOS given the old GLIBC version dependencies. However, you'll be able to build from source without issue.

For building from source you need a C compiler. I was able to build from source on an Amazon Linux 2 with the following. Note that `gcc` must be installed.

```
$ wget 'https://go.dev/dl/go1.17.6.linux-amd64.tar.gz'
$ sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.17.6.linux-amd64.tar.gz
$ echo "export PATH=$PATH:/usr/local/go/bin" | sudo tee -a /etc/profile && . /etc/profile
$ sudo yum install gcc git
$ git clone https://github.com/etclabscore/core-geth.git && cd core-geth
$ make all >/dev/null 2>&1 && echo ok || echo nogo
ok
[ec2-user@ip-172-31-8-89 core-geth]$ ./build/bin/geth version
CoreGeth
Version: 1.12.4-unstable
Git Commit: 200514552516bfb6f8169e4372e182dcf4f51f5f
Git Commit Date: 20220110
Architecture: amd64
Go Version: go1.17.6
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```

See also
- https://github.com/ethereum/go-ethereum/issues/2590
- https://github.com/ethereum/go-ethereum/issues/20143
- https://stackoverflow.com/questions/35616650/how-to-upgrade-glibc-from-version-2-12-to-2-14-on-centos

**Comment by meowsbits** [comment]
I retract the "improbable" part. I think we need to fix this; 18.04 isn't supported out of the box and IMO should be (CentOS too ;).

My guess at this point is that this happened during our migration to Github Actions to build artifacts instead of Travis CI. There, we're building with `ubuntu-latest`, and might be able to provide a quick fix with `ubuntu-18.04`.

**Comment by lukaszsamson** [comment]
I can see that before the migration to github actions migration it was built on ubuntu 16.06 https://github.com/etclabscore/core-geth/commit/f9fd1dafd0c4351629223188b3082a77aa9092da#

**Comment by kamil-maciejczek** [comment]
@meowsbits Thanks for fix. Would you rebuild and publish last release artifacts (v1.12.4) with support for Glibc 2.26? Or publish new version? Hopefully before Kotti upgrade (Jan 23th 2022).
