### ISSUE TITLE
Ubuntu 18.04.2 LTS not supported anymore?

### ISSUE THREAD

**Issue by got3nks** [etclabscore/multi-geth#443]
`geth[30349]: /home/ethereumclassic/geth: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by /home/ethereumclassic/geth)`

Is there any reason to update to new GLIBC? Ethereum's geth works just fine on this Ubuntu LTS version.

**Comment by meowsbits** [comment]
This is a duplicate of #438, though helpfully noting the impact on another Linux distribution (thanks for the report!). Let's move discussion to that original issue.

**Comment by got3nks** [comment]
Thanks, I will wait for the new binaries.

**Comment by meowsbits** [comment]
https://github.com/etclabscore/core-geth/releases/tag/v1.12.6
