### ISSUE TITLE
cannot load hash/maphash: malformed module path "hash/maphash": missing dot in first path element

### ISSUE THREAD

**Issue by kevin-wad** [etclabscore/multi-geth#454]
#### Steps to reproduce the behaviour
clone repo
install make
install golang

make geth    => fails

fails with following error:
cannot load hash/maphash: malformed module path "hash/maphash": missing dot in first path element

Also tried with last release and got same error

**Comment by meowsbits** [comment]
We need more information to be able to help you. System (OS, Go, repo) versions. Have you checked https://etclabscore.github.io/core-geth/developers/build-from-source/ ?
