### ISSUE TITLE
Will MintME's contract address collision fix work for deterministic-address (CREATE2) contracts?

### ISSUE THREAD

**Issue by jessiepathfinder** [etclabscore/multi-geth#462]
I saw that for regular smart contract deployments, you guys implemented a nonce transition for MintME. The nonce transition doesn't seem to be applied to deterministic-address (CREATE2) contracts. Will the contract address collision occur with deterministic-address (CREATE2) contracts?

**Comment by meowsbits** [comment]
See https://github.com/etclabscore/core-geth/pull/400.
@lukaszmatczak, know this one?

**Comment by lukaszmatczak** [comment]
@jessielesbian @meowsbits Since CREATE2 doesn't use nonce to calculate hash, seems it's not affected.

**Comment by meowsbits** [comment]
Considering this closed. Please reopen if your question persists, @jessielesbian. Thanks @lukaszmatczak.
