### ISSUE TITLE
bloombits problem with Cybele (v1.12.6)

### ISSUE THREAD

**Issue by alptolga** [etclabscore/multi-geth#465]
I couldn't find a proper way to sync because of bloombits. Can you help me?

**Comment by alptolga** [comment]
How can I keep geth from bloombits error?

**Comment by meowsbits** [comment]
At the least we can try to help ). If you'll please include information how you're running `geth` and include the logs from around the time(s) you're having issues, that'll help us to help you.

**Comment by alptolga** [comment]
@meowsbits 
I got his error now. I  started the sync and it stopped with this error

CRIT [03-29|11:14:21.495] Failed to store fast sync trie progress  err="leveldb/table: corruption on data-block (pos=1505615): checksum mismatch, want=0x4e2bb9ef got=0x3c14f0d2 [file=033485.ldb]"

when I try started the geth again it stopped again

sudo ./geth --classic --cache 512 console
INFO [03-29|13:11:53.984] Starting Geth on Ethereum Classic... 
INFO [03-29|13:11:53.987] Maximum peer count                       ETH=50 LES=0 total=50
INFO [03-29|13:11:53.988] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [03-29|13:11:53.988] Set global gas cap                       cap=50,000,000
INFO [03-29|13:11:54.005] Configured Ethereum protocol versions    capabilities=[66]
INFO [03-29|13:11:54.005] Allocated trie memory caches             clean=76.00MiB dirty=128.00MiB
INFO [03-29|13:11:54.005] Allocated cache and file handles         database=/home/tt/.ethereum/classic/geth/chaindata cache=256.00MiB handles=2048
INFO [03-29|13:11:54.067] Opened ancient database                  database=/home/tt/.ethereum/classic/geth/chaindata/ancient readonly=false
INFO [03-29|13:11:54.264] Persisted trie from memory database      nodes=12356 size=1.78MiB time=33.119054ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [03-29|13:11:54.265] Found stored genesis block               config="NetworkID: 1, ChainID: 61 Engine: ethash ECBP1100: 11380000 EIP1014: 9573000 EIP1052: 9573000 EIP1108: 10500839 EIP1344: 10500839 EIP140: 8772000 EIP145: 9573000 EIP150: 2500000 EIP152: 10500839 EIP155: 3000000 EIP160: 3000000 EIP161abc: 8772000 EIP161d: 8772000 EIP170: 8772000 EIP1884: 10500839 EIP198: 8772000 EIP2028: 10500839 EIP211: 8772000 EIP212: 8772000 EIP213: 8772000 EIP214: 8772000 EIP2200: 10500839 EIP2565: 13189133 EIP2718: 13189133 EIP2929: 13189133 EIP2930: 13189133 EIP2: 1150000 EIP3529: 14525000 EIP3541: 14525000 EIP658: 8772000 EIP7: 1150000 EthashECIP1010Continue: 5000000 EthashECIP1010Pause: 3000000 EthashECIP1017: 5000000 EthashECIP1041: 5900000 EthashECIP1099: 11700000 EthashEIP100B: 8772000 EthashHomestead: 1150000 "
CRIT [03-29|13:11:54.279] Failed to store chain config             err="leveldb/table: corruption on data-block (pos=1505615): checksum mismatch, want=0x4e2bb9ef got=0x3c14f0d2 [file=033485.ldb]"

**Comment by alptolga** [comment]
> At the least we can try to help ). If you'll please include information how you're running `geth` and include the logs from around the time(s) you're having issues, that'll help us to help you.




I found the problem. geth found bad peers and it is not possible to sync. I need  peerlist to add from console. How can I find?
Can you help me?

**Comment by meowsbits** [comment]
`geth console` or `geth attach`. Then, `admin.peers`, `admin.addPeer`, etc.

**Comment by alptolga** [comment]
> `geth console` or `geth attach`. Then, `admin.peers`, `admin.addPeer`, etc.

In the past, I was able to sync to the etc network with geth and parity without any problems. I can't do it with core geth neither on ubuntu 18.04 nor on windows 10. Whatever I've done since last Saturday my sync attempts end up with bloombits. There is no solution anywhere about this issue. This is something to be ashamed of for a coin that has been on the market for years.
![bbits](https://user-images.githubusercontent.com/23561317/161137259-45da8069-103e-4157-b3d4-c2cf68e816ea.png)

**Comment by meowsbits** [comment]
From your comment above:

```
CRIT [03-29|13:11:54.279] Failed to store chain config err="leveldb/table: corruption on data-block (pos=1505615): checksum mismatch, want=0x4e2bb9ef got=0x3c14f0d2 [file=033485.ldb]"
```

^ This looks like a corrupt database problem. Somewhere down low in the LevelDB internals. Database corruptions like this are often associated with hard kills of the program, sometimes by the operating system (not by pressing `CTL+C`). The easy solution to this is remove the datadir and resync.

The screenshot in your latest comment looks to me like a working client. It reports an imported latest block number `14,836,836`, which is (now) very near to the current head of the chain, which is `14,837,498` at the time of writing.

**Comment by alptolga** [comment]
> From your comment above:
> 
> ```
> CRIT [03-29|13:11:54.279] Failed to store chain config err="leveldb/table: corruption on data-block (pos=1505615): checksum mismatch, want=0x4e2bb9ef got=0x3c14f0d2 [file=033485.ldb]"
> ```
> 
> ^ This looks like a corrupt database problem. Somewhere down low in the LevelDB internals. Database corruptions like this are often associated with hard kills of the program, sometimes by the operating system (not by pressing `CTL+C`). The easy solution to this is remove the datadir and resync.
> 
> The screenshot in your latest comment looks to me like a working client. It reports an imported latest block number `14,836,836`, which is (now) very near to the current head of the chain, which is `14,837,498` at the time of writing.

I never killed and running again. After bloombits it is not posible to sync. I lived this problem with 2 different pc with different os. There must be a chain backup to download for sync for this kind of issues.

**Comment by meowsbits** [comment]
- What is leading you to the conclusion that bloombits in particular is the problem?
- What does not syncing look like for you? Is `eth_blockNumber` stuck at some value? Is `eth_syncing` returning `false`?

**Comment by meowsbits** [comment]
Unfortunately I am unable to reproduce your issue, or understand exactly what the issue is you're having. If you can provide more detailed information about the bug you're encountering, please do so and reopen the issue.
