### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by jessiepathfinder** [etclabscore/multi-geth#468]
root@mintme:~# ./geth --mintme --http --http.port 8545 --http.addr 127.0.0.1 --syncmode full --http.corsdomain "*"
INFO [04-18|04:49:48.891] Starting Geth on MintMe.com Coin mainnet...
INFO [04-18|04:49:48.892] Maximum peer count                       ETH=50 LES=0 total=50
INFO [04-18|04:49:48.892] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [04-18|04:49:48.913] Sanitizing cache to Go's GC limits       provided=1024 updated=323
INFO [04-18|04:49:48.913] Set global gas cap                       cap=50,000,000
INFO [04-18|04:49:49.039] Configured Ethereum protocol versions    capabilities=[66]
INFO [04-18|04:49:49.039] Allocated trie memory caches             clean=48.00MiB dirty=80.00MiB
INFO [04-18|04:49:49.040] Allocated cache and file handles         database=/root/.ethereum/mintme/geth/chaindata cache=160.00MiB handles=524,288
INFO [04-18|04:49:49.072] Opened ancient database                  database=/root/.ethereum/mintme/geth/chaindata/ancient readonly=false
INFO [04-18|04:49:50.106] Persisted trie from memory database      nodes=55777 size=7.60MiB time=133.536585ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=-313568.00B
INFO [04-18|04:49:50.106] Found stored genesis block               config="NetworkID: 37480, ChainID: 24734 Engine: lyra2 EIP1014: 0 EIP1052: 0 EIP1108: 0 EIP1344: 0 EIP140: 0 EIP145: 0 EIP150: 0 EIP152: 0 EIP155: 0 EIP160: 0 EIP161abc: 0 EIP161d: 0 EIP170: 0 EIP1884: 0 EIP198: 0 EIP2028: 0 EIP211: 0 EIP212: 0 EIP213: 0 EIP214: 0 EIP2200: 0 EIP2: 0 EIP658: 0 EIP7: 0 Lyra2Nonce: 252500 "
INFO [04-18|04:49:50.107] Initialised chain configuration          config="NetworkID: 37480, ChainID: 24734 Engine: lyra2 EIP1014: 0 EIP1052: 0 EIP1108: 0 EIP1344: 0 EIP140: 0 EIP145: 0 EIP150: 0 EIP152: 0 EIP155: 0 EIP160: 0 EIP161abc: 0 EIP161d: 0 EIP170: 0 EIP1884: 0 EIP198: 0 EIP2028: 0 EIP211: 0 EIP212: 0 EIP213: 0 EIP214: 0 EIP2200: 0 EIP2: 0 EIP658: 0 EIP7: 0 Lyra2Nonce: 252500 "
INFO [04-18|04:49:50.109] Initialising Ethereum protocol           network=37480 dbversion=8
INFO [04-18|04:49:50.179] Loaded most recent local header          number=2,043,319 hash=98bf90..3140bd td=16,320,408,545,963 age=23h56m45s
INFO [04-18|04:49:50.180] Loaded most recent local full block      number=2,043,100 hash=7db196..fcbdbe td=16,318,823,353,995 age=1d50m2s
INFO [04-18|04:49:50.180] Loaded most recent local fast block      number=2,043,319 hash=98bf90..3140bd td=16,320,408,545,963 age=23h56m45s
INFO [04-18|04:49:50.180] Loaded last fast-sync pivot marker       number=2,043,026
WARN [04-18|04:49:50.198] Failed to load snapshot, regenerating    err="head doesn't match snapshot: have 0x48bcc359208d05193c7b9e8056ad3b525453aa833d72606edb513e21db2c2465, want 0x42464b66bfa70d0d4797ea71b03d2c18dbcc5a2ebb2008abace92e55578c5cd1"
INFO [04-18|04:49:50.198] Rebuilding state snapshot
INFO [04-18|04:49:50.199] Loaded local transaction journal         transactions=0 dropped=0
INFO [04-18|04:49:50.199] Regenerated local transaction journal    transactions=0 accounts=0
INFO [04-18|04:49:50.200] Gasprice oracle is ignoring threshold set threshold=2
WARN [04-18|04:49:50.200] Unclean shutdown detected                booted=2022-04-17T04:45:52+0000 age=1d3m58s
WARN [04-18|04:49:50.200] Unclean shutdown detected                booted=2022-04-18T04:46:29+0000 age=3m21s
WARN [04-18|04:49:50.200] Unclean shutdown detected                booted=2022-04-18T04:47:43+0000 age=2m7s
INFO [04-18|04:49:50.200] Starting peer-to-peer node               instance=CoreGeth/v1.12.6-stable-20d20d72/linux-amd64/go1.17.6
INFO [04-18|04:49:50.208] Resuming state snapshot generation       root=42464b..8c5cd1 accounts=0 slots=0 storage=0.00B elapsed=10.120ms
INFO [04-18|04:49:50.317] New local node record                    seq=1,650,167,896,383 id=7018c3ecd29a41d4 ip=127.0.0.1 udp=30303 tcp=30303
INFO [04-18|04:49:50.346] Started P2P networking                   self=enode://c969db4b6e5a359b33322341ea0acf55799b90594cfe378fbd5d3d0cf206c2a2a6917bfe320df992371d19a7853556fb82731ba09a3b2be231153e20d221d5ae@127.0.0.1:30303
INFO [04-18|04:49:50.387] IPC endpoint opened                      url=/root/.ethereum/mintme/geth.ipc
INFO [04-18|04:49:50.388] HTTP server started                      endpoint=127.0.0.1:8545 prefix= cors=* vhosts=localhost
INFO [04-18|04:49:51.100] Generated state snapshot                 accounts=27328 slots=74145 storage=7.22MiB elapsed=901.289ms
INFO [04-18|04:49:55.160] New local node record                    seq=1,650,167,896,384 id=7018c3ecd29a41d4 ip=209.250.249.167 udp=30303 tcp=30303
INFO [04-18|04:50:00.559] Looking for peers                        peercount=0 tried=94 static=0
INFO [04-18|04:50:00.566] Block synchronisation started
INFO [04-18|04:50:00.744] Downloader queue stats                   receiptTasks=0 blockTasks=0 itemSize=69.90B throttle=8192
INFO [04-18|04:50:00.761] Importing sidechain segment              start=2,043,282 end=2,043,338
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9af4c9]

goroutine 4404 [running]:
github.com/ethereum/go-ethereum/core/types.(*Block).Number(...)
        /home/runner/work/core-geth/core-geth/core/types/block.go:286
github.com/ethereum/go-ethereum/core.(*BlockChain).reorg(0xc0000b3900, 0xc0041ed220)
        /home/runner/work/core-geth/core-geth/core/blockchain.go:2080 +0x669
github.com/ethereum/go-ethereum/core.(*BlockChain).writeBlockWithState(0xc0000b3900, 0xc00422b200, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0xc008715ba0, 0x0)
        /home/runner/work/core-geth/core-geth/core/blockchain.go:1348 +0x1f05
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc0000b3900, {0xc004127000, 0x39, 0x40}, 0x0)
        /home/runner/work/core-geth/core-geth/core/blockchain.go:1749 +0x22b7
github.com/ethereum/go-ethereum/core.(*BlockChain).insertSideChain(0xc0000b3900, 0x174f72c, 0xc004346cf8)
        /home/runner/work/core-geth/core-geth/core/blockchain.go:1932 +0x1b52
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc0000b3900, {0xc003dc4d98, 0x1, 0x1}, 0x1)
        /home/runner/work/core-geth/core-geth/core/blockchain.go:1588 +0xd9f
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc0000b3900, {0xc003dc4d98, 0x1, 0x1})
        /home/runner/work/core-geth/core-geth/core/blockchain.go:1436 +0xb54
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).importBlockResults(0xc002d92700, {0xc003dc4d90, 0x1, 0xc00064a7b0})
        /home/runner/work/core-geth/core-geth/eth/downloader/downloader.go:1736 +0x48a
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent(0xc002d92700)
        /home/runner/work/core-geth/core-geth/eth/downloader/downloader.go:1710 +0x85
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1()
        /home/runner/work/core-geth/core-geth/eth/downloader/downloader.go:579 +0x70
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
        /home/runner/work/core-geth/core-geth/eth/downloader/downloader.go:579 +0x65

Running on latest ubuntu linux VPS + geth

**Comment by meowsbits** [comment]
Thanks for this report. It looks like the panic was because geth found an "impossible reorg," and tried to log block information it didn't have. 

If you'd like to try the `master` version now, it should fix this issue. If you'd prefer to wait for a release, we're planning to make one very soon, and that should address the problem, too.

**Comment by HebeBlock** [comment]
> Thanks for this report. It looks like the panic was because geth found an "impossible reorg," and tried to log block information it didn't have.
> 
> If you'd like to try the `master` version now, it should fix this issue. If you'd prefer to wait for a release, we're planning to make one very soon, and that should address the problem, too.

I also encountered this problem, when will a new version be released?


INFO [06-08|16:40:44.791] HTTP server started                      endpoint=127.0.0.1:8545 prefix= cors=* vhosts=localhost
INFO [06-08|16:40:47.237] New local node record                    seq=1,654,578,187,924 id=b683d8909a2ba92b ip=192.168.1.2 udp=30303 tcp=30303
INFO [06-08|16:40:47.577] Mapped network port                      proto=tcp extport=30303 intport=30303 interface="UPNP IGDv1-IP1"
INFO [06-08|16:40:48.022] Mapped network port                      proto=udp extport=30303 intport=30303 interface="UPNP IGDv1-IP1"
INFO [06-08|16:40:54.831] Looking for peers                        peercount=0 tried=22 static=0
INFO [06-08|16:41:05.115] Looking for peers                        peercount=2 tried=27 static=0
INFO [06-08|16:41:15.147] Looking for peers                        peercount=0 tried=30 static=0
INFO [06-08|16:41:25.161] Looking for peers                        peercount=0 tried=29 static=0
INFO [06-08|16:41:35.248] Looking for peers                        peercount=1 tried=38 static=0
INFO [06-08|16:41:45.252] Looking for peers                        peercount=1 tried=26 static=0
INFO [06-08|16:41:55.515] Looking for peers                        peercount=0 tried=31 static=0
INFO [06-08|16:42:05.572] Looking for peers                        peercount=1 tried=27 static=0
INFO [06-08|16:42:15.736] Looking for peers                        peercount=1 tried=20 static=0
INFO [06-08|16:42:21.385] Block synchronisation started 
INFO [06-08|16:42:21.556] Downloader queue stats                   receiptTasks=0 blockTasks=61 itemSize=57.00B throttle=8192
INFO [06-08|16:42:21.580] Importing sidechain segment              start=15,290,102 end=15,290,138
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4598ae9]

goroutine 1942 [running]:
github.com/ethereum/go-ethereum/core/types.(*Block).Number(...)
	/Users/runner/work/core-geth/core-geth/core/types/block.go:286
github.com/ethereum/go-ethereum/core.(*BlockChain).reorg(0xc0001a7900, 0xc004ca28c0)
	/Users/runner/work/core-geth/core-geth/core/blockchain.go:2080 +0x669
github.com/ethereum/go-ethereum/core.(*BlockChain).writeBlockWithState(0xc0001a7900, 0xc0004b8fc0, {0xc000010be8, 0x1, 0x1}, {0xc000010bf0, 0x1, 0x1}, 0xc0064a96c0, 0x0)
	/Users/runner/work/core-geth/core-geth/core/blockchain.go:1348 +0x1f05
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc0001a7900, {0xc008526c00, 0x25, 0x40}, 0x0)
	/Users/runner/work/core-geth/core-geth/core/blockchain.go:1749 +0x22b7
github.com/ethereum/go-ethereum/core.(*BlockChain).insertSideChain(0xc0001a7900, 0x53ebeab, 0xc001f5ccf8)
	/Users/runner/work/core-geth/core-geth/core/blockchain.go:1932 +0x1b52
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc0001a7900, {0xc00851fb00, 0x1, 0x1}, 0x1)
	/Users/runner/work/core-geth/core-geth/core/blockchain.go:1588 +0xd9f
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc0001a7900, {0xc00851fb00, 0x1, 0x1})
	/Users/runner/work/core-geth/core-geth/core/blockchain.go:1436 +0xb54
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).importBlockResults(0xc0007d16c0, {0xc00851faf8, 0x1, 0x0})
	/Users/runner/work/core-geth/core-geth/eth/downloader/downloader.go:1736 +0x48a
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent(0xc0007d16c0)
	/Users/runner/work/core-geth/core-geth/eth/downloader/downloader.go:1710 +0x85
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1()
	/Users/runner/work/core-geth/core-geth/eth/downloader/downloader.go:579 +0x70
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
	/Users/runner/work/core-geth/core-geth/eth/downloader/downloader.go:579 +0x65

**Comment by meowsbits** [comment]
Hey there @HebeBlock and @jessielesbian -- thanks for your patience. We just released [v1.12.7](https://github.com/etclabscore/core-geth/releases/tag/v1.12.7) which includes the fix for this issue.
