### ISSUE TITLE
Gray Glacier hard fork

### ISSUE THREAD

**Issue by adetante** [etclabscore/multi-geth#482]
Will [the upstream 1.10.19 release](https://github.com/ethereum/go-ethereum/releases/tag/v1.10.19) be merged before the hard fork (https://blog.ethereum.org/2022/06/16/gray-glacier-announcement/) ?

Will a docker image compatible with the next Ethereum hardfork be available?

Thanks :-)

**Comment by meowsbits** [comment]
Just done @adetante (though looks like you've already seen it) -- and thanks for the bump on this.

**Comment by adetante** [comment]
thanks a lot
