### ISSUE TITLE
Need to update to v1.12.8 before ethereum's Gray Glacier fork?

### ISSUE THREAD

**Issue by vae520283995** [etclabscore/multi-geth#486]

**Comment by meowsbits** [comment]
Yes, if you're running the Ethereum mainnet, you'll need to update to v1.12.8 to support the Gray Glacier fork.

**Comment by Alexei-P** [comment]
@meowsbits do you know when Gray Glacier fork will be on ETC?

**Comment by vae520283995** [comment]
> Yes, if you're running the Ethereum mainnet, you'll need to update to v1.12.8 to support the Gray Glacier fork.

Sorry, I didn't describe it clearly, I mean does ethereum classic need to be upgraded?

**Comment by meowsbits** [comment]
No, Ethereum Classic will not have a Gray Glacier fork. (ETC removed the difficulty bomb a few years ago.) You do not need to upgrade for ETC.

**Comment by vae520283995** [comment]
> No, Ethereum Classic will not have a Gray Glacier fork. (ETC removed the difficulty bomb a few years ago.) You do not need to upgrade for ETC.

okay, thank you
