### ISSUE TITLE
'Bug in new version 1.12.9'

### ISSUE THREAD

**Issue by zrock23** [etclabscore/multi-geth#519]
I I think that a program does not create the following paths at startup(mintme network)?🎉:
--ethash.cachedir
--ethash.dagdir

**Comment by ziogaschr** [comment]
I am going to have a look. Thanks

**Comment by ziogaschr** [comment]
I think that **mintme** doesn't use a DAG and this is why it's not being written.

@lukaszmatczak is the maintainer of the mintme implementation and can inform us on this.

**Comment by lukaszmatczak** [comment]
@ziogaschr You're right. Hashing algorithm used in mintme doesn't utilize a DAG.

**Comment by ziogaschr** [comment]
I am closing this issue @zrock23. Feel free to re-open it if you want to provide further explanation on your use case.
