### ISSUE TITLE
v1.12.9 high cpu usage

### ISSUE THREAD

**Issue by Notation** [etclabscore/multi-geth#524]
Hello, after upgrading from v1.12.8 to v1.12.9, the cpu usage of core-geth continues to be high. How can I solve this problem? HDD io is OK

#### System information
- core-geth info:
CoreGeth
Version: 1.12.9-stable
Git Commit: c17c5ae18e393971d3f7910330305526d902e422
Architecture: amd64
Go Version: go1.18.10
Operating System: linux
GOPATH=
GOROOT=/opt/hostedtoolcache/go/1.18.10/x64
- system info: 
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz
Stepping:                        7
CPU MHz:                         2500.014
BogoMIPS:                        5000.02
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        4 MiB
L3 cache:                        35.8 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Vulnerable
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 s
                                 s ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid tsc_known_freq pni p
                                 clmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16
                                 c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ibrs ibpb stibp fsgsbase tsc_adjus
                                 t bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap avx512cd avx512bw a
                                 vx512vl xsaveopt xsavec xgetbv1 arat

#### Expected behaviour
less cpu usage

#### Actual behaviour
**v1.12.8** 
<img width="883" alt="image" src="https://user-images.githubusercontent.com/5916064/217058769-f74aadd8-e8f1-4988-af42-dc8e29724a84.png">

**v1.12.9**
<img width="882" alt="image" src="https://user-images.githubusercontent.com/5916064/217058199-65ff764e-a9a2-4717-9d6d-8b8deee0e5b3.png">

#### Steps to reproduce the behaviour
upgrade from v1.12.8 to v1.12.9

#### Backtrace

**Comment by meowsbits** [comment]
Thanks for the report. I'm just in the middle of looking at this now. 

`txSenderCacher` seems suspect.

```
ia@ianuc:~/Downloads$ go tool pprof profile\(2\)                                                                                                                                                                
File: geth                                                                                                                                                                                                      Build ID: 2a4f22ee8855c29f44a2a89684537cf6e595fa37                                                                                                                                                              
Type: cpu                                                                                                                                                                                                       
Time: Feb 6, 2023 at 11:07am (PST)                                                                                                                                                                              
Duration: 5.18s, Total samples = 57.12s (1102.14%)                                                                                                                                                              Entering interactive mode (type "help" for commands, "o" for options)                                                                                                                                           
(pprof) top                                                                                                                                                                                                     
Showing nodes accounting for 57.04s, 99.86% of 57.12s total                                                                                                                                                     Dropped 34 nodes (cum <= 0.29s)                                                                         
      flat  flat%   sum%        cum   cum%                                                                                                                                                                      
    21.40s 37.46% 37.46%     57.05s 99.88%  github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache                                                                                                        
    15.99s 27.99% 65.46%     21.36s 37.39%  runtime.chanrecv                                                                                                                                                    
    14.28s 25.00% 90.46%     35.64s 62.39%  runtime.selectnbrecv                                                                                                                                                
     5.37s  9.40% 99.86%      5.37s  9.40%  runtime.empty (inline)         
```
