### ISSUE TITLE
Make geth failure on ubuntu 

### ISSUE THREAD

**Issue by Iftikhar3Mustafa** [etclabscore/multi-geth#542]
HI there,

On my computer running "make geth" fails on ubuntu 18.04 LTS.

System information
Geth version: geth version Iris (v1.12.11)
OS & Version: 18.04
Go version 1.20.1 ubuntu/amd64
Make verision 4.1
Commit hash : f5a9595

Expected behaviour
"make geth" or "make all" should work

Actual behaviour
Error

Steps to reproduce the behaviour
Install Go (version windows/amd64) and Make (version 4.4)
cd to /core-geth
run "make geth" fails with errors:

env GO111MODULE=on go run build/ci.go install ./cmd/geth
>>> /usr/lib/go-1.17/bin/go build -ldflags "-extldflags '-Wl,-z,stack-size=0x800000'" -tags urfave_cli_no_docs -v -o /home/asif/Documents/core-geth-1.12.11/core-geth-1.12.11/build/bin/geth ./cmd/geth
golang.org/x/exp/constraints
github.com/deckarep/golang-set/v2
# golang.org/x/exp/constraints
../../../go/pkg/mod/golang.org/x/exp@v0.0.0-20230206171751-46f607a40771/constraints/constraints.go:13:2: syntax error: unexpected ~, expecting method or interface name
../../../go/pkg/mod/golang.org/x/exp@v0.0.0-20230206171751-46f607a40771/constraints/constraints.go:20:2: syntax error: unexpected ~, expecting method or interface name
../../../go/pkg/mod/golang.org/x/exp@v0.0.0-20230206171751-46f607a40771/constraints/constraints.go:27:9: syntax error: unexpected |, expecting semicolon or newline or }
../../../go/pkg/mod/golang.org/x/exp@v0.0.0-20230206171751-46f607a40771/constraints/constraints.go:34:2: syntax error: unexpected ~, expecting method or interface name
../../../go/pkg/mod/golang.org/x/exp@v0.0.0-20230206171751-46f607a40771/constraints/constraints.go:41:2: syntax error: unexpected ~, expecting method or interface name
../../../go/pkg/mod/golang.org/x/exp@v0.0.0-20230206171751-46f607a40771/constraints/constraints.go:49:10: syntax error: unexpected |, expecting semicolon or newline or }
note: module requires Go 1.18
# github.com/deckarep/golang-set/v2
../../../go/pkg/mod/github.com/deckarep/golang-set/v2@v2.1.0/iterator.go:30:17: syntax error: unexpected comparable, expecting ]
../../../go/pkg/mod/github.com/deckarep/golang-set/v2@v2.1.0/iterator.go:36:18: syntax error: unexpected [, expecting comma or )
../../../go/pkg/mod/github.com/deckarep/golang-set/v2@v2.1.0/iterator.go:39:15: method has no receiver
../../../go/pkg/mod/github.com/deckarep/golang-set/v2@v2.1.0/iterator.go:39:15: syntax error: unexpected {, expecting name or (
../../../go/pkg/mod/github.com/deckarep/golang-set/v2@v2.1.0/iterator.go:51:17: syntax error: unexpected [, expecting (
../../../go/pkg/mod/github.com/deckarep/golang-set/v2@v2.1.0/set.go:41:12: syntax error: unexpected comparable, expecting ]
../../../go/pkg/mod/github.com/deckarep/golang-set/v2@v2.1.0/set.go:131:19: syntax error: unexpected ), expecting (
../../../go/pkg/mod/github.com/deckarep/golang-set/v2@v2.1.0/set.go:139:2: syntax error: non-declaration statement outside function body
../../../go/pkg/mod/github.com/deckarep/golang-set/v2@v2.1.0/set.go:180:12: syntax error: unexpected [, expecting (
../../../go/pkg/mod/github.com/deckarep/golang-set/v2@v2.1.0/set.go:190:24: syntax error: unexpected [, expecting (
../../../go/pkg/mod/github.com/deckarep/golang-set/v2@v2.1.0/set.go:190:24: too many errors
note: module requires Go 1.18
github.com/ethereum/go-ethereum/event
# github.com/ethereum/go-ethereum/event
event/feedof.go:28:15: syntax error: unexpected any, expecting ]
event/feedof.go:39:16: syntax error: unexpected [, expecting comma or )
event/feedof.go:51:16: syntax error: unexpected [, expecting comma or )
event/feedof.go:66:16: syntax error: unexpected [, expecting comma or )
event/feedof.go:90:16: syntax error: unexpected [, expecting comma or )
event/feedof.go:148:18: syntax error: unexpected any, expecting ]
event/feedof.go:155:21: syntax error: unexpected [, expecting comma or )
event/feedof.go:156:24: method has no receiver
event/feedof.go:156:24: syntax error: unexpected {, expecting name or (
event/feedof.go:162:21: syntax error: unexpected [, expecting comma or )
event/feedof.go:162:21: too many errors
note: module requires Go 1.19
github.com/ethereum/go-ethereum/common/lru
# github.com/ethereum/go-ethereum/common/lru
common/lru/basiclru.go:24:17: syntax error: unexpected comparable, expecting ]
common/lru/basiclru.go:30:18: syntax error: unexpected any, expecting ]
common/lru/basiclru.go:36:17: syntax error: unexpected [, expecting (
common/lru/basiclru.go:49:18: syntax error: unexpected [, expecting comma or )
common/lru/basiclru.go:59:20: syntax error: unexpected [ after top level declaration
common/lru/basiclru.go:77:18: syntax error: unexpected [, expecting comma or )
common/lru/basiclru.go:83:18: syntax error: unexpected [, expecting comma or )
common/lru/basiclru.go:94:18: syntax error: unexpected [, expecting comma or )
common/lru/basiclru.go:105:18: syntax error: unexpected [, expecting comma or )
common/lru/basiclru.go:110:18: syntax error: unexpected [, expecting comma or )
common/lru/basiclru.go:110:18: too many errors
note: module requires Go 1.19
github.com/ethereum/go-ethereum/internal/version
# github.com/ethereum/go-ethereum/internal/version
internal/version/vcs.go:33:24: info.Settings undefined (type *debug.BuildInfo has no field or method Settings)
note: module requires Go 1.19
util.go:48: exit status 2
exit status 1
Makefile:13: recipe for target 'geth' failed
make: *** [geth] Error 1

Thank you so much for help!

**Comment by meowsbits** [comment]
> /usr/lib/go-1.17/bin/go build 
> ...
> note: module requires Go 1.19

Suggests that you may in fact not be on "Go version 1.20.1 ubuntu/amd64", rather on Go 1.17. Can you verify?

**Comment by Iftikhar3Mustafa** [comment]
Thank you,

The problem has been resolved.
