### ISSUE TITLE
Iris (v1.12.11)  Fatal: Failed to start mining: ether base missing: ether base must be explicitly specified

### ISSUE THREAD

**Issue by Iftikhar3Mustafa** [etclabscore/multi-geth#543]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

System information
Geth version: geth version Iris (v1.12.11)
OS & Version: 18.04
Go to version 1.10.4 ubuntu/amd64
Make version 4.1

Run the signer node by Geth:

This error occurred:

INFO [05-17|06:02:14.481] Transaction pool price threshold updated price=0
INFO [05-17|06:02:14.481] Updated mining threads                   threads=0
INFO [05-17|06:02:14.481] Transaction pool price threshold updated price=1,000,000,000
ERROR[05-17|06:02:14.481] Cannot start mining without ether base    err="ether base must be explicitly specified"
Fatal: Failed to start mining: ether base missing: ether base must be explicitly specified

Please help me Thank you 

The previous release Kronos (v1.12.10) is working fine on my AWS machine But this new one got an error mentioned above

**Comment by meowsbits** [comment]
The "etherbase" is the account that should be credited with block rewards and gas fees when you win a block. 
Geth's behavior has indeed changed in the last release; you now need to use the CLI option to configure it (whereas in earlier versions, the first account in the keystore was selected by default).  

```
./build/bin/geth --help|grep -A5 -B5 etherbase
   MINER
   
    --mine                         (default: false)
          Enable mining
   
    --miner.etherbase value       
          0x prefixed public address for block mining rewards
   
    --miner.extradata value       
          Block extra data set by the miner (default = client version)
```

PS. :warning: The command you're using there seems to be high risk.

**Comment by Iftikhar3Mustafa** [comment]
Hi Sir, 

Blockchain has started mining now after adding this parameter --miner.etherbase value in this command. Please verify me
Does it work fine and find out blocks in pool?
 
./Geth-EthereumClassic/geth --datadir "/media/ubuntu/EthereumClassic/.ethereumclassic" --classic --nousb --password "/media/ubuntu/EthereumClassic/.walletpass" --http.api "eth,web3,net,personal,db" --http --mine --allow-insecure-unlock --unlock 0 --http.port 8546 --port 30304 --miner.etherbase public wallet address.

Thank you.

**Comment by meowsbits** [comment]
Yes, that should work for you. But again, please be aware that using `--unlock --http --http.api "...personal" --mine` will allow anyone with access to those HTTP ports to withdraw the funds you may earn by mining.

**Comment by Iftikhar3Mustafa** [comment]
Sure Sir Acknowledged Thank you
.
