### ISSUE TITLE
Synchronisation failed, dropping peer err=timeout  Iris (v1.12.11)

### ISSUE THREAD

**Issue by Iftikhar3Mustafa** [etclabscore/multi-geth#547]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

System information
Geth version: geth version Iris (v1.12.11)
OS & Version: 18.04
Go to version 1.20.4 ubuntu/amd64
Make version 4.1

Run the signer node by Geth:

This error occurred:
Peer delivering stale transaction 
![26-ETC-May-2023-GETH-AWS](https://github.com/etclabscore/core-geth/assets/54815154/a5a3afec-27e7-41cd-8d71-917c0074915f)
Please help me Thank you

**Comment by meowsbits** [comment]
I don't see any issues; that looks like normal behavior to me. Stale transactions are rejected; new, eligible transactions are being accumulated for block 17600750; and incremental chain segment imports are happening.

**Comment by Iftikhar3Mustafa** [comment]
Thank you.
