### ISSUE TITLE
Recommended to use fork-diff for the transparent view with upstream geth

### ISSUE THREAD

**Issue by ghost** [etclabscore/multi-geth#584]
Hello,

I would like to recommend using forkdiff https://github.com/protolambda/forkdiff to produce diffs with upstream geth so that it could help merging upstream changes and help people understand what is the difference.

Example from op-geth: https://op-geth.optimism.io/

**Comment by ziogaschr** [comment]
Thanks for the suggestion @kaliubuntu0206. This was already on our list to have a look at forkdiff.
