### ISSUE TITLE
Could you please confirm whether it is mandatory to update to the latest release, Real Eris (v1.12.16), or if the previous version is sufficient for the mainet client? 

### ISSUE THREAD

**Issue by Iftikhar3Mustafa** [etclabscore/multi-geth#585]
Hello, 

I would like to confirm the current release of Real Eris (v1.12.16). Is it mandatory to update it on the server? Currently, I am using the previous release that came out two weeks ago, Eris (v1.12.15). What are the differences between the two versions, and is it necessary to update to the latest one? Please confirm for me. I am waiting for a positive response. Thanks.

 The current release of Real Eris (v1.12.16). Is it mandatory to update it on the server? 
 
 I am using the previous release that came out two weeks ago, Eris (v1.12.15). 

@meowsbits Your confirmation on the preferred version would be appreciated. Thank you.

**Comment by ziogaschr** [comment]
The only difference between v1.12.15 and v1.12.16 is that it has the block number defined for the Spiral hardfork on **Mordor Testnet**. There is no need to update to it if you run a node on **Classic Mainnet**.

**Comment by Iftikhar3Mustafa** [comment]
Ok, Thank you.
