### ISSUE TITLE
deactivate MESS on Mordor

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/multi-geth#601]
[ECBP-1110](https://github.com/meowsbits/ECIPs/blob/ecbp1110/_specs/ecip-1110.md) specifies MESS's deactivation for ETC, but not Mordor. But Mordor should probably deactivate it too -- thanks [@chris-mercer for the flag on this](https://github.com/etclabscore/core-geth/pull/597#issuecomment-1863647918). 

We'll just need to settle on a block number and add configuration here: https://github.com/etclabscore/core-geth/blob/master/params/config_mordor.go#L96.
Reference for deactivation on Classic: https://github.com/etclabscore/core-geth/blob/master/params/config_classic.go#L85

**Comment by meowsbits** [comment]
I just pushed https://github.com/ethereumclassic/ECIPs/pull/520/commits/a828ae5452eb3f44e194a8d4358f8f387b818b1b to the [ECBP1100 PR](https://github.com/ethereumclassic/ECIPs/pull/520) proposing deactivation for Mordor at 10,400,000, which should be in something like 4 days from now (10400000 - 10374238 =~ 25000 / 6400 blocks / day => ~4 days).

**Comment by ziogaschr** [comment]
I agree with the suggestion. This means that we have to create a release asap.
