### ISSUE TITLE
 Synchronisation failed

### ISSUE THREAD

**Issue by 0xZonh** [etclabscore/multi-geth#610]
I upgraded the geth version from v1.12.13 to v1.12.18 today, and then it seems that the blocks cannot be synchronized normally. I'm a newbie and can't figure out where the problem is.
![image](https://github.com/etclabscore/core-geth/assets/110391762/de09df05-7de2-456d-8207-b01826fbed3c)

Please let me know if there is a solution for this. Thank you!

**Comment by meowsbits** [comment]
Hey there @0xZonh, thanks for the report. You're not alone on this, but we have no precise diagnostic or workarounds for now.

See the referenced issue above for further context on (what seems to be) your issue. 

And please, if you can include more of your context, it will be helpful to us to better understand the issue; your CLI configuration, any relevant firewall configuration on the host, how long you've been dealing with the problem, etc.

**Comment by ziogaschr** [comment]
@0xZonh can we also know your location (if allowed to be shared) please, in order we check on a node in the same location as you. It might need more time to find good nodes close to you, and we might be able to find the cause and resolve it easier.

**Comment by lixiubao4967** [comment]
I also have the above problem, how to solve it? How long does it take to find a peer?
WARN [01-30|17:58:55.238] Synchronisation failed, dropping peer    peer=9ab3b037eb1c892569115fb9e97fdc6aa2b8bc5c9a712b1f449cacf53a763dee err=timeout
WARN [01-30|17:59:25.904] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
WARN [01-30|17:59:49.244] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
WARN [01-30|18:00:00.589] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
WARN [01-30|18:00:27.415] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
WARN [01-30|18:01:16.414] Synchronisation failed, retrying         err="peer is unknown or unhealthy"

**Comment by ziogaschr** [comment]
Can you please try using these 3 peers (current bootnodes) by hand?

```
enode://6b6ea53a498f0895c10269a3a74b777286bd467de6425c3b512740fcc7fbc8cd281dca4ab041dd97d62b38f3d0b5b05e71f48d28a3a2f4b5de40fe1f6bf05531@157.245.77.211:30303

enode://16264d48df59c3492972d96bf8a39dd38bab165809a3a4bb161859a337de38b2959cc98efea94355c7a7177cd020867c683aed934dbd6bc937d9e6b61d94d8d9@64.225.0.245:30303

enode://55bbc7f0ffa2af2ceca997ec195a98768144a163d389ae87b808dff8a861618405c2582451bbb6022e429e4bcd6b0e895e86160db6e93cdadbcfd80faacf6f06@164.90.144.106:30303
```

**Comment by lixiubao4967** [comment]
It should be that the speed of finding peers is relatively slow. Now it is observed that synchronization has started. Thank you for your reply.

INFO [01-30|22:11:04.058] Syncing: chain download in progress      synced=95.82% chain=20.47GiB headers=18,428,891@5.33GiB bodies=18,412,049@12.20GiB receipts=18,412,049@2.94GiB eta=25m36.866s
INFO [01-30|22:11:04.063] Syncing: state healing in progress       accounts=0@0.00B slots=0@0.00B codes=0@0.00B nodes=2858@1.06MiB   pending=2181
INFO [01-30|22:11:04.135] Loaded most recent local header          number=18,426,842 hash=f5e125..ef7d48 td=6,621,534,149,745,222,344,099 age=4mo1d18h
INFO [01-30|22:11:04.135] Loaded most recent local block           number=0          hash=d4e567..cb8fa3 td=17,179,869,184                age=54y10mo1w
INFO [01-30|22:11:04.135] Loaded most recent local snap block      number=18,412,049 hash=502db0..618035 td=6,593,180,674,639,825,555,472 age=4mo4d1h
INFO [01-30|22:11:04.135] Loaded last snap-sync pivot marker       number=19,214,245
WARN [01-30|22:11:04.135] Rolled back chain segment                header=18428891->18426842 snap=18412049->18412049 block=0->0 reason="syncing canceled (requested)"
WARN [01-30|22:11:04.135] Synchronisation failed, retrying         err="no peers to keep download active"
INFO [01-30|22:11:11.703] Regenerated local transaction journal    transactions=0 accounts=0
INFO [01-30|22:11:12.743] Looking for peers                        peercount=1 tried=42 static=0
INFO [01-30|22:11:23.076] Looking for peers                        peercount=2 tried=38 static=0
INFO [01-30|22:11:33.265] Looking for peers                        peercount=2 tried=35 static=0
INFO [01-30|22:11:43.408] Looking for peers                        peercount=2 tried=36 static=0

**Comment by lixiubao4967** [comment]
@ziogaschr 
How do I specify these three peers?
enode://6b6ea53a498f0895c10269a3a74b777286bd467de6425c3b512740fcc7fbc8cd281dca4ab041dd97d62b38f3d0b5b05e71f48d28a3a2f4b5de40fe1f6bf05531@157.245.77.211:30303

enode://16264d48df59c3492972d96bf8a39dd38bab165809a3a4bb161859a337de38b2959cc98efea94355c7a7177cd020867c683aed934dbd6bc937d9e6b61d94d8d9@64.225.0.245:30303

enode://55bbc7f0ffa2af2ceca997ec195a98768144a163d389ae87b808dff8a861618405c2582451bbb6022e429e4bcd6b0e895e86160db6e93cdadbcfd80faacf6f06@164.90.144.106:30303

**Comment by ziogaschr** [comment]
If you started core-geth with console command, like `geth --classic console` then you can type there `admin.addPeer('enode://6b6ea53a498f0895c10269a3a74b777286bd467de6425c3b512740fcc7fbc8cd281dca4ab041dd97d62b38f3d0b5b05e71f48d28a3a2f4b5de40fe1f6bf05531@157.245.77.211:30303')`.
If you use JSON RPC APIs and you have `admin` API open (which is not advised), then you can use https://etclabscore.github.io/core-geth/JSON-RPC-API/modules/admin/#admin_addpeer

**Comment by jakubartur** [comment]
me the same no sync ,  look number=19,218,133 hash=d66d06..7f6820 td=8,164,776,887,095,361,374,446 age=7h58m44s
7h+ no sync fix
> admin.addPeer('enode://55bbc7f0ffa2af2ceca997ec195a98768144a163d389ae87b808dff8a861618405c2582451bbb6022e429e4bcd6b0e895e86160db6e93cdadbcfd80faacf6f06@164.90.144.106:30303')
true
> admin.addPeer('enode://16264d48df59c3492972d96bf8a39dd38bab165809a3a4bb161859a337de38b2959cc98efea94355c7a7177cd020867c683aed934dbd6bc937d9e6b61d94d8d9@64.225.0.245:30303')
true
> admin.addPeer('enode://16264d48df59c3492972d96bf8a39dd38bab165809a3a4bb161859a337de38b2959cc98efea94355c7a7177cd020867c683aed934dbd6bc937d9e6b61d94d8d9@64.225.0.245:30303')
true
Looking for peers                        peercount=0 tried=57 static=2
bootnodes limit 50 peers no open slots conect ??

I suggest you do something similar to what I did, please check the link https://enode.redecoin.eu/

**Comment by jakubartur** [comment]
INFO [01-31|12:42:46.138] Block synchronisation started
INFO [01-31|12:42:54.157] Looking for peers                        peercount=1 tried=55 static=3
INFO [01-31|12:43:04.280] Looking for peers                        peercount=0 tried=51 static=3
INFO [01-31|12:43:14.466] Looking for peers                        peercount=0 tried=37 static=3
INFO [01-31|12:43:24.607] Looking for peers                        peercount=0 tried=51 static=3
INFO [01-31|12:43:34.686] Looking for peers                        peercount=1 tried=60 static=3
INFO [01-31|12:43:44.799] Looking for peers                        peercount=1 tried=47 static=3
WARN [01-31|12:43:46.138] Synchronisation failed, dropping peer    peer=5d1706ab63f92532c709f6c611b6c0f0e508d5f328be9615c689896280bdb328 err=timeout

bootnode problem conect

**Comment by ziogaschr** [comment]
Once this new release https://github.com/etclabscore/core-geth/releases/tag/v1.12.19 is being used on more nodes in the network, we will probably not have more peering issues. Please update yourselfs.

**Comment by MiningCryptoLive** [comment]
I am trying to sync using the latest version and on classic network and it is taking forever. Used to be able to sync within a couple hours. I am now going on 24 hours and only at 46% downloaded with 66 peers connected.@ziogaschr

**Comment by ziogaschr** [comment]
> I am trying to sync using the latest version and on classic network and it is taking forever. Used to be able to sync within a couple hours. I am now going on 24 hours and only at 46% downloaded with 66 peers connected.@ziogaschr

Thanks @MiningCryptoLive. Starting a fresh node now to test it.

**Comment by ziogaschr** [comment]
I was able to sync latest release on classic in 3 hours. Check the green line @MiningCryptoLive.

Can you share which CLI flags you use to run it and also what OS? I was running it on Ubuntu.

<img width="1098" alt="image" src="https://github.com/user-attachments/assets/3c5f18a7-4f71-46ee-9f5c-db52bc5c9635">

**Comment by MiningCryptoLive** [comment]
> I was able to sync latest release on classic in 3 hours. Check the green line @MiningCryptoLive.
> 
> Can you share which CLI flags you use to run it and also what OS? I was running it on Ubuntu.
> 
> <img alt="image" width="1098" src="https://private-user-images.githubusercontent.com/802700/359488852-3c5f18a7-4f71-46ee-9f5c-db52bc5c9635.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNzM2MzYsIm5iZiI6MTcyNDE3MzMzNiwicGF0aCI6Ii84MDI3MDAvMzU5NDg4ODUyLTNjNWYxOGE3LTRmNzEtNDZlZS05ZjVjLWRiNTJiYzVjOTYzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQxNzAyMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjA1NmE0NTJkOWNhYmU3ODYzNDhkOTQ2ZmEwYTAzODBiZGMwYWRiNmU1Nzk4ZmM0YWJiZDNiNjQzM2EwNjJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VZ9eMDs_fm3y52-Mh6Up5wKpb63sUJN_YzNdfcqalEw">

Here is my command line: geth --classic --datadir /home/pool/.ethereum/classic --syncmode=snap --http --http.api eth,net,web3 --mine --miner.etherbase="0x********" --maxpeers 100 --password="/home/pool/.pw" --allow-insecure-unlock --http.port="8545" --unlock="0x******" --port="30305" I am running this on Ubuntu 22.04 @ziogaschr

**Comment by MiningCryptoLive** [comment]
I also downloaded geth again. Deleted the.ethereum directory & started syncing again. 4 1/2 hours later and only.15 percent download with 66 peers. Something is definitely wrong

**Comment by ziogaschr** [comment]
Can you try and start syncing without the `--mine` flag. Restart and enable `--mine` once synced.

Does your machine have enough resources?

**Comment by MiningCryptoLive** [comment]
Yes plenty of resources. I removed the flag —mine. Deleted the
directory.ethereum and restarted geth. An hour in and it’s almost synced.

Randy Hasson
199 East Markison Avenue
Columbus, Ohio 43207

**Comment by ziogaschr** [comment]
Perfect. Let me know if you can mine once synced.
I will check if we can handle that flow better.

p.s.: You probably have your machine behind a firewall and with all ports closed already. If not needed I will advice to remove the `--http` flag.

**Comment by MiningCryptoLive** [comment]
I will remove that and let you know once synced and flags added back if mining works

**Comment by MiningCryptoLive** [comment]
@ziogaschr  Get the following after sync completed and enabled mining. All daemons online. All daemons synced with blockchain. Loading current light cache. No pre-generated cache available. Unable to mine.

**Comment by ziogaschr** [comment]
Can you share logs? Do you mine with CPU or GPU? Are you connecting to a pool (which one?)?

**Comment by MiningCryptoLive** [comment]
> Can you share logs? Do you mine with CPU or GPU? Are you connecting to a pool (which one?)?

I am using gpu's. Mining to a pool. I am assuming that the changes made has affected the mining pool software. That is what is showing that the light cache does not exist. And then it shuts down. I will try a different mining pool software and see if it works. I'll let you know. Thanks for all your help!

**Comment by MiningCryptoLive** [comment]
> Can you share logs? Do you mine with CPU or GPU? Are you connecting to a pool (which one?)?

I tried different pool software and mining works fine.

**Comment by ziogaschr** [comment]
Thanks a lot for sharing.

Can you please let me know which pool is not working and which one works? (please share link to repos if you can)

**Comment by MiningCryptoLive** [comment]
> Thanks a lot for sharing.
> 
> Can you please let me know which pool is not working and which one works? (please share link to repos if you can)

this is the one I am using now and it works fine.

https://github.com/yuriy0803/open-etc-pool-friends

Miningcore is now not working. I am assuming the code needs to be modified. It starts then shuts down at Loading current light cache ... No pre-generated cache available.

https://github.com/blackmennewstyle/miningcore

**Comment by ziogaschr** [comment]
Thanks @MiningCryptoLive.
I will close this issue now.

**Comment by MiningCryptoLive** [comment]
Also wanted to let you know that I left geth syncing on another machine with all the flags in place. It is almost done syncing after 2 days but it also takes double the storage space. Syncing without the flags takes 48gb and with the flags 151gb so far

**Comment by MiningCryptoLive** [comment]
Also wanted to let you know that I left geth syncing on another machine with all the flags in place. It is almost done syncing after 2 days but it also takes double the storage space. Syncing without the flags takes 48gb and with the flags 151gb so far
________________________________

**Comment by ziogaschr** [comment]
I was expecting that, and also at some point, probably on a restart, geth will prune the data (still cover all the difference in size).

**Comment by MiningCryptoLive** [comment]
Ok, thanks.
