### ISSUE TITLE
Synchronisation failed-Persiphone (v1.12.19)

### ISSUE THREAD

**Issue by Iftikhar3Mustafa** [etclabscore/multi-geth#619]
I upgraded the geth version from v1.12.18 to v1.12.19 today, and then it seems that the blocks cannot be synchronized normally. I'm a newbie and can't figure out where the problem is.

![Uploading syncronize-failed.png…]()

Please let me know if there is a solution for this. Thank you!

Looking for peers                        peercount=0 tried=47 static=0
Feb 09 09:46:24 ip-172-31-42-109 geth[453]: WARN [02-09|09:46:24.524] Synchronisation failed, dropping peer    peer=1cb6639418d4981d7b9b655733d721ff7209ef6417d6074ccfe90a4597f6c1cf err=timeout
Feb 09 09:46:24 ip-172-31-42-109 geth[453]: INFO [02-09|09:46:24.524] Commit new sealing work                  number=19,277,270 sealhash=c3d1d3..766a58 uncles=0 txs=0 gas=0 fees=0 elapsed="236.435µs"
Feb 09 09:46:24 ip-172-31-42-109 geth[453]: INFO [02-09|09:46:24.524] Commit new sealing work                  number=19,277,270 sealhash=c3d1d3..766a58 uncles=0 txs=0 gas=0 fees=0 elapsed="376.596µs"
Feb 09 09:46:32 ip-172-31-42-109 geth[453]: INFO [02-09|09:46:32.868] Looking for peers                        peercount=0 tried=39 static=0
Feb 09 09:46:42 ip-172-31-42-109 geth[453]: INFO [02-09|09:46:42.869] Looking for peers                        peercount=0 tried=38 static=0
Feb 09 09:46:53 ip-172-31-42-109 geth[453]: INFO [02-09|09:46:53.078] Looking for peers                        peercount=0 tried=47 static=0
Feb 09 09:46:56 ip-172-31-42-109 geth[453]: WARN [02-09|09:46:56.404] Snapshot extension registration failed   peer=bfd22e9c err="peer connected on snap without compatible eth support"
Feb 09 09:47:03 ip-172-31-42-109 geth[453]: INFO [02-09|09:47:03.108] Looking for peers                        peercount=0 tried=40 static=0
Feb 09 09:47:08 ip-172-31-42-109 geth[453]: INFO [02-09|09:47:08.835] Mining aborted due to sync
Feb 09 09:47:13 ip-172-31-42-109 geth[453]: INFO [02-09|09:47:13.202] Looking for peers                        peercount=0 tried=39 static=0
Feb 09 09:47:23 ip-172-31-42-109 geth[453]: INFO [02-09|09:47:23.203] Looking for peers                        peercount=0 tried=48 static=0
Feb 09 09:47:33 ip-172-31-42-109 geth[453]: INFO [02-09|09:47:33.221] Looking for peers                        peercount=1 tried=45 static=0
Feb 09 09:47:43 ip-172-31-42-109 geth[453]: INFO [02-09|09:47:43.222] Looking for peers                        peercount=0 tried=30 static=0
Feb 09 09:47:53 ip-172-31-42-109 geth[453]: INFO [02-09|09:47:53.536] Looking for peers                        peercount=0 tried=40 static=0
Feb 09 09:48:03 ip-172-31-42-109 geth[453]: INFO [02-09|09:48:03.537] Looking for peers                        peercount=0 tried=38 static=0
Feb 09 09:48:08 ip-172-31-42-109 geth[453]: WARN [02-09|09:48:08.836] Synchronisation failed, dropping peer    peer=d12a64813d8a11e3e4259ae004b36e155666008877b07e44da311f61beb5decf err=timeout

**Comment by Iftikhar3Mustafa** [comment]
![Uploading syncronize-failed.png…]()

**Comment by Iftikhar3Mustafa** [comment]
Hi,

The Geth version v1.12.18 is working absolutely fine. However, I am facing synchronization issues with version v1.12.19. The process of looking for peers repeats continuously. I'm unsure of what's causing this issue. If there are any potential impacts due to this issue, please update me.

If I cannot update to the latest version, how will it impact my mining process? Please guide me as I am worried about it. Thanks.
@meowsbits

**Comment by ziogaschr** [comment]
@Iftikhar3Mustafa thanks for the report. I will retry to reproduce it now. 

This release has [small changes](https://github.com/etclabscore/core-geth/compare/v1.12.18...v1.12.19) that doesn't impact your mining process.

**Comment by ziogaschr** [comment]
It started syncing now for me (will wait for it to finish). I see a lot of `TRACE[02-12|15:32:26.730] Failed p2p handshake                     id=*** addr=****  conn=dyndial err="too many peers"` in the logs, which means that the nodes that are reachable in the network are still low. :(

Using the https://etcnodes.org/ portal and sorting on "Version" I've seen that clients haven't updated to "v1.12.19" yet which was going to help on having more publicly serving nodes in the network, so we have to wait.

What you report though, has to be examined, which is that v1.12.19 was having issues, while v1.12.18 worked. There is still the explanation, that v1.12.19 would have worked the same after a restart of the node, but it's better that we examine and be sure that this is the case.

**Comment by Iftikhar3Mustafa** [comment]
I need to confirm whether version 1.12.18 works fine for mining and if blocks will generate, or if it will impact the mining process. When you check out the issues with the new update, please guide me about it. I am waiting for it and using version 1.12.18 until the new release resolves the problem. Thanks.

**Comment by ziogaschr** [comment]
I will update you. I confirm that v1.12.18 is great for you to continue till we test.

**Comment by Iftikhar3Mustafa** [comment]
Great to hear that version 1.12.18 is working well for me! Feel free to update me once you've completed your testing. Thanks.

**Comment by meowsbits** [comment]
@Iftikhar3Mustafa 

> I am facing synchronization issues with version v1.12.19. The process of looking for peers repeats continuously.

How long have you waited for synchronization to start? Your logs span less than 2 minutes. I would give it at least 10 minutes before suspecting that anything is wrong.

All versions of core-geth that we release are intended to be OK for mining.

**Comment by Iftikhar3Mustafa** [comment]
Here's the corrected version of your text:

"Hello, the other version of Geth normally starts synchronization within 10 minutes and imports chain segments when a new release, v1.12.19, comes out on the website. I decided to upgrade from v1.12.18 to v1.12.19, but I am facing issues. This release has been causing synchronization failures for a long time. It continuously searches for peers, and the synchronization process repeats. Sometimes synchronization starts, but then the same process repeats. After waiting for seven to eight hours for synchronization with no results, I reverted to my previous release, v1.12.18, which I am currently using. I always upgrade my Geth blockchain when a new release is available on the ETC website."

**Comment by Iftikhar3Mustafa** [comment]
Hello, the other version of Geth normally starts synchronization within 10 minutes and imports chain segments when a new release, v1.12.19, comes out on the website. I decided to upgrade from v1.12.18 to v1.12.19, but I am facing issues. This release has been causing synchronization failures for a long time. It continuously searches for peers, and the synchronization process repeats. Sometimes synchronization starts, but then the same process repeats. After waiting for seven to eight hours for synchronization with no results, I reverted to my previous release, v1.12.18, which I am currently using. I always upgrade my Geth blockchain when a new release is available on the ETC website.

**Comment by meowsbits** [comment]
One possible workaround for you might be to nuke the nodes datadir, and optionally the `nodekey` too:

```bash
rm -rf /<datadir>/geth/nodes
rm /<datadir>/geth/nodekey
```

This will cause your geth to rebuild the p2p database and might erase anything slowing you down.

Out of curiosity, and if you feel comfortable saying, which part of the world is your geth's internet connection starting from? Geophysical location could influence round trip times and your neighbor peer density.

**Comment by Iftikhar3Mustafa** [comment]
Sir, so if I remove the node and nodekey files from the Geth directory, and then start the new release v1.12.19, the issue of not being able to find peers might be resolved, and it should work for me. Okay, let's try it, and I'll update you. Thanks.

**Comment by ziogaschr** [comment]
@Iftikhar3Mustafa where your issues resolved? Can we close this issue?

**Comment by Iftikhar3Mustafa** [comment]
Hi, my problem was resolved as you instructed me in our previous
conversations. Sorry for not updating you earlier. I am now closing this
issue.

I also wanted to ask about the current problem with block generation on the
pool side. It has been 23 days since the last block was generated. My
current hashrate is 3.52, and I am wondering if the difficulty is high or
if there are other issues causing this. Please guide me as I am worried
about it. Thanks.

**Comment by ziogaschr** [comment]
@Iftikhar3Mustafa  Great to hear about the sync issues.

Can you please let us know if you mine directly or using a pool.
What is the command you use to mine with geth (please hide you coinbase and anything else not needed)?
I wonder if you leave the `--miner.gaslimit` to the default 30M (which is not advised for ETC) or you change this to the preferred 8M (https://github.com/etclabscore/core-geth/pull/620)

**Comment by Iftikhar3Mustafa** [comment]
I am using the pool to mine ETC blocks. I have spent 25 days, but no block
has been generated. The latest blockchain is updated to v1.12.19
(Persiphone). On the pool side, the total hashrate is 3.53GH. Normally, a
block is generated every two or five days, but I'm wondering what's going
on, as it's taking too long without generating any block.

**Comment by Iftikhar3Mustafa** [comment]
Hi sir,

Here are Details of Mining staus of my pool

Please refer to the attached screenshot of the Geth daemon's updated status
on the AWS machine and the command used to run this Geth for mining:

geth --datadir "/media/ubuntu/EthereumClassic/.ethereumclassic" --classic
--nousb --password "/media/ubuntu/EthereumClassic/.walletpass" --http.api
"eth,web3,net,personal,db" --http --mine --allow-insecure-unlock --unlock 0

**Comment by ziogaschr** [comment]
Which pool do you use? Do you what pool software it uses?

**Comment by Iftikhar3Mustafa** [comment]
I am using the Etchaah pool software, which was developed using the Clasito
pool source code from GitHub.

**Comment by Iftikhar3Mustafa** [comment]
Please refer to the attached screenshot for the pool status.

**Comment by ziogaschr** [comment]
I can't see the attached image. Can you give a link to the pool's repository please?

**Comment by ziogaschr** [comment]
Can you better open a new issue?
