### ISSUE TITLE
unreachable bootloaders stop node process

### ISSUE THREAD

**Issue by Phoenix1969** [etclabscore/multi-geth#622]
unreachable bootloaders stop node process
The moment a node attempts to connect to an unreachable bootloader enode the node process crashes and stops.
I then have to remove that enode from config.toml to get it to run.
```There need be an exception made so 1 local power outage isnt crashing nodes globally.```

**Comment by meowsbits** [comment]
Are you still using unresolvable host names? https://github.com/etclabscore/core-geth/issues/612

> Geth is exiting because it can't resolve the host name in your configuration, which its treating like an invalid enode address. You can avoid this error by replacing the host name with an IP, and geth should then tolerate even unavailable bootnodes.

**Comment by sagarroja** [comment]
> Are you still using unresolvable host names? #612
> 
> > Geth is exiting because it can't resolve the host name in your configuration, which its treating like an invalid enode address. You can avoid this error by replacing the host name with an IP, and geth should then tolerate even unavailable bootnodes.

mines too same problem getting from more than 4 days

**Comment by meowsbits** [comment]
@sagarroja What values are you using for bootnode addresses? 

If you're using a domain name, like `mai289.ddns.net`, which fails to resolve (eg. the DNS record is unavailable), then geth will refuse to start.

Per [this comment](https://github.com/etclabscore/core-geth/issues/612#issuecomment-1929282777) you can reference https://ethereum.org/en/developers/docs/networking-layer/network-addresses/#enode, which describes that DNS names are not allowed. So geth allowing them, when they work, is supposed to be a quiet convenience; strictly speaking, it should not allow them at all, and should allow only raw IP values.

**Comment by Phoenix1969** [comment]
> @sagarroja What values are you using for bootnode addresses?
> 
> If you're using a domain name, like `mai289.ddns.net`, which fails to resolve (eg. the DNS record is unavailable), then geth will refuse to start.
> 
> Per [this comment](https://github.com/etclabscore/core-geth/issues/612#issuecomment-1929282777) you can reference https://ethereum.org/en/developers/docs/networking-layer/network-addresses/#enode, which describes that DNS names are not allowed. So geth allowing them, when they work, is supposed to be a quiet convenience; strictly speaking, it should not allow them at all, and should allow only raw IP values.

TYVM, kind Sir!
